import { KeyInfo } from "../types/KeyInfo";

export const allKeys: KeyInfo[] = [
  { name: ['C'], nameInKeyboard: ['C1'], isBlackKey: false, number: 1 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db1', 'C#1'],
    isBlackKey: true,
    number: 2,
  },
  { name: ['D'], nameInKeyboard: ['D1'], isBlackKey: false, number: 3 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb1', 'D#1'],
    isBlackKey: true,
    number: 4,
  },
  { name: ['E'], nameInKeyboard: ['E1'], isBlackKey: false, number: 5 },
  { name: ['F'], nameInKeyboard: ['F1'], isBlackKey: false, number: 6 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb1', 'F#1'],
    isBlackKey: true,
    number: 7,
  },
  { name: ['G'], nameInKeyboard: ['G1'], isBlackKey: false, number: 8 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab1', 'Gb1'],
    isBlackKey: true,
    number: 9,
  },
  { name: ['A'], nameInKeyboard: ['A1'], isBlackKey: false, number: 10 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb1', 'A#1'],
    isBlackKey: true,
    number: 11,
  },
  { name: ['B'], nameInKeyboard: ['B1'], isBlackKey: false, number: 12 },
  { name: ['C'], nameInKeyboard: ['C2'], isBlackKey: false, number: 13 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db2', 'C#2'],
    isBlackKey: true,
    number: 14,
  },
  { name: ['D'], nameInKeyboard: ['D2'], isBlackKey: false, number: 15 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb2', 'D#2'],
    isBlackKey: true,
    number: 16,
  },
  { name: ['E'], nameInKeyboard: ['E2'], isBlackKey: false, number: 17 },
  { name: ['F'], nameInKeyboard: ['F2'], isBlackKey: false, number: 18 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb2', 'F#2'],
    isBlackKey: true,
    number: 19,
  },
  { name: ['G'], nameInKeyboard: ['G2'], isBlackKey: false, number: 20 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab2', 'Gb2'],
    isBlackKey: true,
    number: 21,
  },
  { name: ['A'], nameInKeyboard: ['A2'], isBlackKey: false, number: 22 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb2', 'A#2'],
    isBlackKey: true,
    number: 23,
  },
  { name: ['B'], nameInKeyboard: ['B2'], isBlackKey: false, number: 24 },
  { name: ['C'], nameInKeyboard: ['C3'], isBlackKey: false, number: 25 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db3', 'C#3'],
    isBlackKey: true,
    number: 26,
  },
  { name: ['D'], nameInKeyboard: ['D3'], isBlackKey: false, number: 27 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb3', 'D#3'],
    isBlackKey: true,
    number: 28,
  },
  { name: ['E'], nameInKeyboard: ['E3'], isBlackKey: false, number: 29 },
  { name: ['F'], nameInKeyboard: ['F3'], isBlackKey: false, number: 30 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb3', 'F#3'],
    isBlackKey: true,
    number: 31,
  },
  { name: ['G'], nameInKeyboard: ['G3'], isBlackKey: false, number: 32 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab3', 'Gb3'],
    isBlackKey: true,
    number: 33,
  },
  { name: ['A'], nameInKeyboard: ['A3'], isBlackKey: false, number: 34 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb3', 'A#3'],
    isBlackKey: true,
    number: 35,
  },
  { name: ['B'], nameInKeyboard: ['B3'], isBlackKey: false, number: 36 },
  { name: ['C'], nameInKeyboard: ['C4'], isBlackKey: false, number: 37 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db4', 'C#4'],
    isBlackKey: true,
    number: 38,
  },
  { name: ['D'], nameInKeyboard: ['D4'], isBlackKey: false, number: 39 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb4', 'D#4'],
    isBlackKey: true,
    number: 40,
  },
  { name: ['E'], nameInKeyboard: ['E4'], isBlackKey: false, number: 41 },
  { name: ['F'], nameInKeyboard: ['F4'], isBlackKey: false, number: 42 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb4', 'F#4'],
    isBlackKey: true,
    number: 43,
  },
  { name: ['G'], nameInKeyboard: ['G4'], isBlackKey: false, number: 44 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab4', 'Gb4'],
    isBlackKey: true,
    number: 45,
  },
  { name: ['A'], nameInKeyboard: ['A4'], isBlackKey: false, number: 46 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb4', 'A#4'],
    isBlackKey: true,
    number: 47,
  },
  { name: ['B'], nameInKeyboard: ['B4'], isBlackKey: false, number: 48 },
  { name: ['C'], nameInKeyboard: ['C5'], isBlackKey: false, number: 49 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db5', 'C#5'],
    isBlackKey: true,
    number: 50,
  },
  { name: ['D'], nameInKeyboard: ['D5'], isBlackKey: false, number: 51 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb5', 'D#5'],
    isBlackKey: true,
    number: 52,
  },
  { name: ['E'], nameInKeyboard: ['E5'], isBlackKey: false, number: 53 },
  { name: ['F'], nameInKeyboard: ['F5'], isBlackKey: false, number: 54 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb5', 'F#5'],
    isBlackKey: true,
    number: 55,
  },
  { name: ['G'], nameInKeyboard: ['G5'], isBlackKey: false, number: 56 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab5', 'Gb5'],
    isBlackKey: true,
    number: 57,
  },
  { name: ['A'], nameInKeyboard: ['A5'], isBlackKey: false, number: 58 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb5', 'A#5'],
    isBlackKey: true,
    number: 59,
  },
  { name: ['B'], nameInKeyboard: ['B5'], isBlackKey: false, number: 60 },
  { name: ['C'], nameInKeyboard: ['C6'], isBlackKey: false, number: 61 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db6', 'C#6'],
    isBlackKey: true,
    number: 62,
  },
  { name: ['D'], nameInKeyboard: ['D6'], isBlackKey: false, number: 63 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb6', 'D#6'],
    isBlackKey: true,
    number: 64,
  },
  { name: ['E'], nameInKeyboard: ['E6'], isBlackKey: false, number: 65 },
  { name: ['F'], nameInKeyboard: ['F6'], isBlackKey: false, number: 66 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb6', 'F#6'],
    isBlackKey: true,
    number: 67,
  },
  { name: ['G'], nameInKeyboard: ['G6'], isBlackKey: false, number: 68 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab6', 'Gb6'],
    isBlackKey: true,
    number: 69,
  },
  { name: ['A'], nameInKeyboard: ['A6'], isBlackKey: false, number: 70 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb6', 'A#6'],
    isBlackKey: true,
    number: 71,
  },
  { name: ['B'], nameInKeyboard: ['B6'], isBlackKey: false, number: 72 },
  { name: ['C'], nameInKeyboard: ['C7'], isBlackKey: false, number: 73 },
  {
    name: ['Db', 'C#'],
    nameInKeyboard: ['Db7', 'C#7'],
    isBlackKey: true,
    number: 74,
  },
  { name: ['D'], nameInKeyboard: ['D7'], isBlackKey: false, number: 75 },
  {
    name: ['Eb', 'D#'],
    nameInKeyboard: ['Eb7', 'D#7'],
    isBlackKey: true,
    number: 76,
  },
  { name: ['E'], nameInKeyboard: ['E7'], isBlackKey: false, number: 77 },
  { name: ['F'], nameInKeyboard: ['F7'], isBlackKey: false, number: 78 },
  {
    name: ['Gb', 'F#'],
    nameInKeyboard: ['Gb7', 'F#7'],
    isBlackKey: true,
    number: 79,
  },
  { name: ['G'], nameInKeyboard: ['G7'], isBlackKey: false, number: 80 },
  {
    name: ['Ab', 'G#'],
    nameInKeyboard: ['Ab7', 'Gb7'],
    isBlackKey: true,
    number: 81,
  },
  { name: ['A'], nameInKeyboard: ['A7'], isBlackKey: false, number: 82 },
  {
    name: ['Bb', 'A#'],
    nameInKeyboard: ['Bb7', 'A#7'],
    isBlackKey: true,
    number: 83,
  },
  { name: ['B'], nameInKeyboard: ['B7'], isBlackKey: false, number: 84 },
]
